function [y]=int_pot(xp,yp,x,R,h,src_type);

% INPUT
% xp,yp    - coordinates of some point laying in the support of a 
%          - basis element centered at (0,0)
% x        - x - coordinate of a point (x,0) at which we calculate the
%          - potential
% R        - radius of the basis element
% h
% src_type - type of basis function in the source space
%            (step/gauss/gauss_lim)

% OUTPUT
% int_pot - contribution of a point xp,yp, belonging to a basis source
%         - support centered at (0,0) to the potential measured at (x,0)
%         - , integrated over xp,yp gives the potential generated by a 
%         - basis source element centered at (0,0) at point (x,0)  

    y=sqrt((x-xp).^2+yp.^2);
    y(y<0.00001)=0.00001;
    y=asinh(h./y);
    R2=R.^2;
    switch src_type
        case 'step'
            y=y.*(xp.^2+yp.^2<=R2);
        case 'gauss'
            y=y.*gauss2D_rescale(xp,yp,[0,0],R);
        case 'gauss_lim'
            y=y.*gauss2D_rescale_lim(xp,yp,[0,0],R);
        otherwise
            error(['Source type: ' src_type ' is not valid.'])
    end;
